manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: northisup
      url-base: https://github.com/NorthIsUp
  projects:
    - name: zmk
      remote: northisup
      revision: adv360-z4.1
      import: app/west.yml
  self:
    path: config
